server {
    listen 80;
    # NGINX Path that written in 'docker-compose.yml'
    root /var/www/html;

    index index.html index.php;

    # Performing common static pages of the site
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # must be this block for PHP
    location ~ \.php$ {
        # Instead of IP-addr typing "php" from 'docker-compose.yml' and its port 9000
        fastcgi_pass php:9000; 
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}